version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test  
    ports:
      - "0.0.0.0:4040:8080"  # Map host port 8080 to container port 3000
    networks:
      - digitalkitchen-network-test  # Attach frontend service to the custom network
    container_name: digitalkitchen-frontend-test

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.test
    ports:
      - "4000:8000"  # Map host port 8000 to container port 80
    networks:
      - digitalkitchen-network-test  # Attach frontend service to the custom network
    container_name: digitalkitchen-backend-test

networks:
  digitalkitchen-network-test:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"  # Disable IPv6 to use only IPv4
    ipam:
      config:
        - subnet: 192.168.11.0/24
          gateway: 192.168.11.1
