version: '3'
services:
  frontend:
    build: ./frontend/
    ports:
      - "8080:3000"  # Map host port 8080 to container port 3000

  backend:
    image: ./backend/
    ports:
      - "8000:80"  # Map host port 8000 to container port 80

networks:
  my_network:
    driver: bridge

