version: '3'
services:
  #frontend:
    #build: ./frontend/
    #ports:
      #- "8080:8080"  # Map host port 8080 to container port 8080
    #networks:
      #- digitalkitchen-network
    #container_name: digitalkitchen-frontend
    #image: digitalkitchen-frontend

  backend:
    build: ../backend
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    networks:
      - digitalkitchen-network
    container_name: digitalkitchen-backend
    image: digitalkitchen-backend

networks:
  digitalkitchen-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
