version: '3'
services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4040:4040"  # Map host port 4040 to container port 4040
    networks:
      - digitalkitchen-network-dev
    container_name: digitalkitchen-frontend-dev

  backend-dev:
    build: 
      context: ../backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"  # Map host port 4000 to container port 4000
    networks:
      - digitalkitchen-network-dev
    container_name: digitalkitchen-backend-dev

networks:
  digitalkitchen-network-dev:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: 192.168.11.0/24
          gateway: 192.168.11.1
