FROM openjdk:17-jdk

WORKDIR /app

# Copy all JAR files to /app directory
COPY ../target/app.jar .

# Set app.jar as the CMD to be executed
CMD ["java", "-jar", "-Dspring.profiles.active=dev", "app.jar"]

