name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Run deployment script
        run: sudo /opt/digitalkitchen/scripts/deploy_digitalkitchen-backend.sh

